import.meta.url;import("_").catch(()=>1);async function* g(){};if(location.protocol!="file:"){window.__vite_is_modern_browser=true}

!function(){if(window.__vite_is_modern_browser)return;console.warn("vite: loading legacy chunks, syntax error above and the same error below should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();


                window.preloadData = {'config':{'slug':'reanime-status','title':'Re:ANIME','description':'Find what is going on with Re:ANIME','icon':'/upload/logo1.png?t=1781352177632','theme':'auto','published':true,'showTags':false,'customCSS':'body {\n  \n}\n','footerText':null,'showPoweredBy':false,'googleAnalyticsId':null,'showCertificateExpiry':false},'incident':{'id':2,'style':'warning','title':'Attack on Re:ANIME(Monitoring)','content':'Attackers are back at it again','pin':1,'createdDate':'2026-06-20 16:06:19','lastUpdatedDate':'2026-06-27 01:35:09'},'publicGroupList':[{'id':1,'name':'Re:ANIME','weight':1,'monitorList':[{'id':2,'name':'Re:ANIME(.to)','sendUrl':0,'type':'http'},{'id':3,'name':'Re:ANIME - API','sendUrl':0,'type':'http'}]},{'id':2,'name':'Flixcloud','weight':2,'monitorList':[{'id':5,'name':'Flixcloud','sendUrl':0,'type':'http'},{'id':6,'name':'Flixcloud CDN 1','sendUrl':0,'type':'http'},{'id':7,'name':'Flixcloud CDN 2','sendUrl':0,'type':'http'},{'id':8,'name':'Flixcloud CDN 3','sendUrl':0,'type':'http'},{'id':9,'name':'Flixcloud (Backup)','sendUrl':0,'type':'http'}]}],'maintenanceList':[]};
            

!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();

System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))